
const data = {
  products: [
    {
      _id: 1,
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "https://i.ibb.co/F4zD4Yq/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      descripttion: "High quality shirt",
    },
    {
      _id: 2,
      name: "Lacoste Slim Shirt",
      category: "Shirts",
      image: "https://i.ibb.co/f0cKLDF/p2.jpg",
      price: 110,
      countInStock: 20,
      brand: "Lacoste",
      rating: 4.0,
      numReviews: 8,
      descripttion: "Medium quality shirt",
    },
    {
      _id: 3,
      name: "Khaki Pant",
      category: "Pants",
      image: "https://i.ibb.co/q0PcR33/p3.jpg",
      price: 80,
      countInStock:0,
      brand: "Khaki",
      rating: 3.5,
      numReviews: 15,
      descripttion: "A khaki pant",
    },
    {
      _id: 4,
      name: "Adidas Slim Shirt",
      category: "Shirts",
      image: "https://i.ibb.co/f0cKLDF/p2.jpg",
      price: 30,
      countInStock: 50,
      brand: "Adidas",
      rating: 2.0,
      numReviews: 20,
      descripttion: "Poor quality shirt",
    },
    {
      _id: 5,
      name: "Adidas pant",
      category: "Pants",
      image: "https://i.ibb.co/gdM7CLx/p5.jpg",
      price: 10,
      brand: "Adidas",
      countInStock: 100,
      rating: 0.5,
      numReviews: 2,
      descripttion: "HIgh quality light Khaki pant",
    },
    {
      _id: 6,
      name: "Light Khaki Pant",
      category: "Shirts",
      image: "https://i.ibb.co/q0PcR33/p3.jpg",
      price: 1000,
      countInStock: 2,
      brand: "Khaki",
      rating: 5,
      numReviews: 180,
      descripttion: "High quality shirt deluxe edition",
    },
  ],
};

export default data;
